In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
import pickle

In [48]:
df = pd.read_csv("Churn_Modelling.csv")

In [4]:
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
df.drop(['RowNumber',"CustomerId",'Surname'], axis=1, inplace=True)

In [6]:
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [7]:
df.Geography.value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [49]:
labelencoder_gender=LabelEncoder()
df['Gender']=labelencoder_gender.fit_transform(df['Gender'])
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary  Exited
0          1    15634602  Hargrave  ...               1       101348.88       1
1          2    15647311      Hill  ...               1       112542.58       0
2          3    15619304      Onio  ...               0       113931.57       1
3          4    15701354      Boni  ...               0        93826.63       0
4          5    15737888  Mitchell  ...               1        79084.10       0

[5 rows x 14 columns]

In [16]:
onehotencoder_geography=OneHotEncoder()
geo_encoded = onehotencoder_geography.fit_transform(df[['Geography']]).toarray()

In [18]:
geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehotencoder_geography.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [19]:
df = pd.concat([df.drop('Geography', axis=1),geo_encoded_df], axis=1)
df.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [50]:
with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(labelencoder_gender, file=file)

In [22]:
with open("onehot_encoder_geography.pkl","wb") as file:
    pickle.dump(obj=onehotencoder_geography, file=file)

In [23]:
x=df.drop(['Exited'],axis=1)
y=df['Exited']

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.2, random_state=42)

#scaling:
scaler=StandardScaler()
scaler.fit_transform(x_train)
scaler.transform(x_test)

#creating scaler pickle file
with open("scaler.pkl","wb") as file:
    pickle.dump(obj=scaler, file=file)

## ANN Implementation:

In [25]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [26]:
model = Sequential([
    Dense(64, activation='relu', input_shape=((x_train.shape[1]),)), #Hidden layer 1 connected to inputs
    Dense(32,activation='relu'),        #Hidden layer 2
    Dense(1,activation='sigmoid')       #output layer
    
    
])

d:\Projects\Churn Prediction\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [27]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
opt = tf.keras.optimizers.Adam(learning_rate=0.01)

In [29]:
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [47]:
#set up the tensorboard
log_dir="log/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [32]:
#set up early stopping
earlystopping_callback=EarlyStopping(patience=10,monitor='val_loss',restore_best_weights=True)

In [33]:
#model training:
history=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),
    epochs=100, callbacks=[tensorflow_callback,earlystopping_callback]
)

Epoch 1/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6845 - loss: 1100.4233 - val_accuracy: 0.7943 - val_loss: 214.3391
Epoch 2/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6860 - loss: 168.0677 - val_accuracy: 0.5651 - val_loss: 103.6541
Epoch 3/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6665 - loss: 170.3549 - val_accuracy: 0.7965 - val_loss: 70.7444
Epoch 4/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6950 - loss: 70.3216 - val_accuracy: 0.4459 - val_loss: 44.2641
Epoch 5/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6855 - loss: 54.8960 - val_accuracy: 0.7954 - val_loss: 48.0810
Epoch 6/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6985 - loss: 62.2352 - val_accuracy: 0.4880 - val_loss: 25.0856
Epoch 7/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6695 - loss: 23.4688 - val_accuracy: 0.7966 - val_loss: 55.9635
Epoch 8/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6870 - loss: 28.8059 - val_accuracy: 0.7969 - val_loss: 16.0540
Epoch 9/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6750 - loss: 13.4015 - val_accuracy: 0.7144 - val_loss: 9.2103
Epoch 10/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6915 - loss: 5.4190 - val_accuracy: 0.7830 - val_loss: 2.5827
Epoch 11/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6865 - loss: 5.9184 - val_accuracy: 0.7244 - val_loss: 2.7189
Epoch 12/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6705 - loss: 6.3019 - val_accuracy: 0.7966 - val_loss: 13.5245
Epoch 13/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6805 - loss: 5.3648 - val_accuracy: 0.6251 - val_loss: 1.8560
Epoch 14/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6950 - loss: 2.0649 - val_accuracy: 0.5456 - val_loss: 2.3403
Epoch 15/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6835 - loss: 2.3697 - val_accuracy: 0.6289 - val_loss: 1.1147
Epoch 16/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7030 - loss: 1.4647 - val_accuracy: 0.7321 - val_loss: 1.1844
Epoch 17/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7260 - loss: 0.8085 - val_accuracy: 0.7868 - val_loss: 0.5965
Epoch 18/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7555 - loss: 0.6507 - val_accuracy: 0.6345 - val_loss: 0.6603
Epoch 19/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7360 - loss: 0.7763 - val_accuracy: 0.6037 - val_loss: 1.0349
Epoch 20/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7385 - loss: 0.6441 - val_accuracy: 0.7834 - val_loss: 0.5488
Epoch 21/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7710 - loss: 0.5675 - val_accuracy: 0.7966 - val_loss: 0.6796
Epoch 22/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.5689 - val_accuracy: 0.7914 - val_loss: 0.5315
Epoch 23/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7620 - loss: 0.5839 - val_accuracy: 0.7966 - val_loss: 0.5768
Epoch 24/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7715 - loss: 0.5525 - val_accuracy: 0.7966 - val_loss: 0.6285
Epoch 25/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7820 - loss: 0.5394 - val_accuracy: 0.7705 - val_loss: 0.5494
Epoch 26/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7845 - loss: 0.5399 - val_accuracy: 0.7295 - val_loss: 0.5780
Epoch 27/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7865 - loss: 0.5166 - val_accuracy: 0.7865 - val_loss: 0.5372
Epoch 28/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.5210 - val_accuracy: 0.7962 - val_loss: 0.5226
Epoch 29/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7885 - loss: 0.5347 - val_accuracy: 0.7966 - val_loss: 0.5328
Epoch 30/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7870 - loss: 0.5206 - val_accuracy: 0.7966 - val_loss: 0.5293
Epoch 31/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7930 - loss: 0.5121 - val_accuracy: 0.7966 - val_loss: 0.5263
Epoch 32/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7905 - loss: 0.5072 - val_accuracy: 0.7968 - val_loss: 0.5196
Epoch 33/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7890 - loss: 0.5056 - val_accuracy: 0.7966 - val_loss: 0.5201
Epoch 34/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7930 - loss: 0.5001 - val_accuracy: 0.7936 - val_loss: 0.5273
Epoch 35/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7940 - loss: 0.5011 - val_accuracy: 0.7970 - val_loss: 0.5195
Epoch 36/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7960 - loss: 0.4996 - val_accuracy: 0.7966 - val_loss: 0.5247
Epoch 37/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7945 - loss: 0.4998 - val_accuracy: 0.7969 - val_loss: 0.5155
Epoch 38/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7920 - loss: 0.5014 - val_accuracy: 0.7824 - val_loss: 0.5274
Epoch 39/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7940 - loss: 0.4986 - val_accuracy: 0.7955 - val_loss: 0.5200
Epoch 40/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7955 - loss: 0.4988 - val_accuracy: 0.7961 - val_loss: 0.5170
Epoch 41/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7950 - loss: 0.4969 - val_accuracy: 0.7966 - val_loss: 0.5146
Epoch 42/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7955 - loss: 0.4964 - val_accuracy: 0.7949 - val_loss: 0.5209
Epoch 43/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7960 - loss: 0.4991 - val_accuracy: 0.7968 - val_loss: 0.5145
Epoch 44/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7955 - loss: 0.4969 - val_accuracy: 0.7955 - val_loss: 0.5201
Epoch 45/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7960 - loss: 0.4981 - val_accuracy: 0.7952 - val_loss: 0.5192
Epoch 46/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7955 - loss: 0.4972 - val_accuracy: 0.7965 - val_loss: 0.5145
Epoch 47/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7960 - loss: 0.4972 - val_accuracy: 0.7965 - val_loss: 0.5157
Epoch 48/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7960 - loss: 0.5002 - val_accuracy: 0.7965 - val_loss: 0.5146
Epoch 49/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7960 - loss: 0.4991 - val_accuracy: 0.7969 - val_loss: 0.5145
Epoch 50/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7955 - loss: 0.4976 - val_accuracy: 0.7968 - val_loss: 0.5150
Epoch 51/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7955 - loss: 0.4975 - val_accuracy: 0.7966 - val_loss: 0.5155
Epoch 52/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7955 - loss: 0.4985 - val_accuracy: 0.7965 - val_loss: 0.5156
Epoch 53/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7960 - loss: 0.4986 - val_accuracy: 0.7961 - val_loss: 0.5156

In [34]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [44]:
%reload_ext tensorboard

In [46]:
%tensorboard --logdir log/fit

Reusing TensorBoard on port 6007 (pid 30540), started 0:07:30 ago. (Use '!kill 30540' to kill it.)